import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/Navbar";
import CartProvider from "@/components/providers";
import ShoppingCartModal from "@/components/ShippingCartModal";
import { client } from "@/lib/sanity";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Bookstore",
  description: "Generated by create next app",
};

async function getCategories() {
  const query = "*[_type == 'category']";

  const data = await client.fetch(query);

  return data;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();

  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <Suspense>
            <Navbar categories={categories} />
          </Suspense>
          <ShoppingCartModal />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
